services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx_app
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./docker/php
    container_name: php_app
    volumes:
      - ./app:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network

  mysql:
    build:
      context: ./docker/mysql
    container_name: mysql_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
